pads:
  36:
    name: "Terminal"
    type: simple
    command: "gnome-terminal -- bash -c 'cd ~/ && exec bash'"

  37:
    name: "Chrome"
    type: simple
    command: "google-chrome"

  38:
    name: "Spotify"
    type: simple
    command: "spotify"

  39:
    name: "Postman"
    type: simple
    command: "/opt/Postman/Postman"

  40:
    name: "DBeaver"
    type: simple
    command: "/var/lib/flatpak/app/io.dbeaver.DBeaverCommunity/x86_64/stable/cc737e000cd13ebe4e93b33a5f6a0d877296c6e2ba12b11c9f094909213f8f7c/files/bin/dbeaver"

  44:
    name: "Code Here"
    type: simple
    command: "src/static/scripts/code_here.sh"

  46:
    name: "React Dev"
    type: simple
    command: "src/static/scripts/react_localhost.sh"

  48:
    name: "Bloquear pantalla"
    type: simple
    command: "xdotool key ctrl+alt+l"

  50:
    name: "Arriba la máquina"
    type: simple
    command: "espeak -v es 'arriba la maquina perros'"

  51:
    name: "Payaso"
    type: simple
    command: "espeak -v es payaso"
